export const projectsData = [
  {
    id: 1,
    image: '/assets/everrest.PNG',
    title: 'EverrestGroup',
    category: 'Web',
    link: 'https://everrestgroup.com',
  },
  {
    id: 2,
    image: '/assets/ICGC.PNG',
    title: 'ICGC Prayer Temple',
    category: 'Web',
    link: 'https://darkslategrey-wombat-363454.hostingersite.com/',
  },
  {
    id: 4,
    image: '/assets/hcowa.PNG',
    title: 'Hcowaa',
    category: 'Web',
    link: 'https://hcowa.com/',
  },
  {
    id: 6,
    image: '/assets/myflix.PNG',
    title: 'MyFlix',
    category: 'App',
    link: 'https://myflix-jcasare.vercel.app',
  },
  {
    id: 7,
    image: '/assets/healthpulse.PNG',
    title: 'Healthpulse Online',
    category: 'App',
    link: 'https://healthpulseonline.com/',
  },
  {
    id: 8,
    image: '/assets/ataya-tea.png',
    title: 'Ataya Tea',
    category: 'Web',
    link: 'https://atayatea.com/',
  },
  {
    id: 9,
    image: '/assets/iscript-sys.png',
    title: 'iScript Systems',
    category: 'Web',
    link: 'https://iscriptsystems.com/',
  },
  {
    id: 10,
    image: '/assets/aim-building.png',
    title: 'AIM Building Materials',
    category: 'Web',
    link: 'https://www.aimbuildingmaterials.com/',
  },
  {
    id: 11,
    image: '/assets/bbb-int.png',
    title: 'BBB Interventions',
    category: 'Web',
    link: 'https://bbbinterventions.com/',
  },
  {
    id: 12,
    image: '/assets/fortiffi.png',
    title: 'Fortiffi',
    category: 'App',
    link: 'https://app.fortiffi.com/affiliate-onboarding',
  },
  {
    id: 13,
    image: '/assets/global-trav.png',
    title: 'Global Travel Network',
    category: 'App',
    link: 'https://globaltrips.com/login',
  },
  {
    id: 14,
    image: '/assets/roma-resources.png',
    title: 'Roma Resources',
    category: 'Web',
    link: 'https://romaresources.org/',
  },
  {
    id: 15,
    image: '/assets/elite-energy.png',
    title: 'Elite EnergyRig',
    category: 'Web',
    link: 'https://eliteenergyrig.com/',
  },
];

export const projectsNav = [
  { name: 'All' },
  { name: 'Web' },
  { name: 'App' },
];
